### ISSUE TITLE
"max-line-length" tslint.json Starter Solution error

### ISSUE THREAD

**Issue by simoncrelling** [ispfx/react-crash-course#1] opened 2019-01-06 20:33 UTC
Hi Kyle,
Sorry about raising this as an issue here, but I don't have another way to contact you (perhaps adding a contact section to the course may be a good idea?).
The starter solution (https://github.com/ispfx/react-crash-course/archive/edf7e00748bdba1c024f51e99d9a6f5a53d86f1e.zip) has a small error in the tslint.json file:
```javascript
"max-line-length": [false],
```
should be:
```javascript
"max-line-length": [false]
```

The extra comma causes this error when you **npm run start**:
```
Error: Unexpected token } in JSON at position 348 in F:\Code\react-crash-course\tslint.json
 ```

**Comment by kyleschaeffer** [comment] 2019-01-10 16:30
Hi, @simoncrelling. Thanks for reporting the issue. This was actually resolved in this commit:
https://github.com/ispfx/react-crash-course/commit/daa9efd70136cbc8ef5a5224ae017c8666df9068

The problem is that I often link back to previous commits (which include the old version of `tslint.json`) from the course. I'll up my GIT-game and try to figure out how to amend a previous commit so that this is no longer an issue.

Best,
Kyle

**Comment by kyleschaeffer** [comment] 2019-01-10 16:44
The "download starter solution" link within the course has been updated and the zip file should now contain the correct version of `tsconfig.json` after doing a git rebase.

Thank you again for reporting the issue.

**Closed as completed** 2019-01-10 16:45 UTC
Labels: bug

**Comment by kyleschaeffer** [comment] 2019-01-10 16:46
Also as a follow-up note, you can join the chat room at https://gitter.im/ispfx. I often check into the room and am happy to connect there if you have additional issues. Thank you!
